version : '3'

services:

  app_db:
    container_name: app_db
    # Versão da imagem do banco de dados
    # https://hub.docker.com/_/mariadb/
    image: mariadb:10.5    
    # Mapeamento de diretórios do container para a pasta local
    volumes: 
      - ./docker/mariadb/data:/var/lib/mysql/data
      - ./docker/mariadb/log:/var/lib/mysql/logs
      - ./docker/mariadb/conf:/var/docker/mariadb/conf
    # Configurações do banco de dados
    environment:      
      MYSQL_ROOT_PASSWORD: segredo
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: segredo
    # Expor a porta para conexão fora do docker
    ports:
      - 3306:3306

  app_pma:
    image: phpmyadmin/phpmyadmin
    # Deve ser o mesmo nome do serviço declarado acima
    links:
      - app_db
    environment:
      PMA_HOST: app_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 
      UPLOAD_LIMIT: 30000000000
    ports:
      - 8081:80

  app_web:
    container_name: app_web
    build:
      context: ./docker/php
      dockerfile: php-apache-dockerfile
    links:
      - app_db
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
